% demo_column_test
%  When you do not want to process all the columns at once


obs_id = '9036';
% crism_obs = CRISMObservation(obs_id,'SENSOR_ID','L');
crism_obs_info = crism_get_obs_info(obs_id,'SENSOR_ID','L', ...
        'Download_DDR',2,'Download_EDRSCDF',2, ...
        'Download_TRRIF',2,'ext_trrif','lbl', ...
        'Download_TRRRA',2,'ext_trrra','lbl','Download_TRRRAHKP',2,...
        'DWLD_INDEX_CACHE_UPDATE',false);
TRRIFdata = CRISMdata(crism_obs.info.basenameIF,crism_obs.info.dir_trdr);
TRRIFdata.load_basenamesCDR('Dwld',2,'Index_cache_update',trues);
[Yif] = crism_calibration_IR_v2(obs_id,'save_memory',true,'mode','yuki2', ...
    'version','B','skip_ifexist',0,'force',1,'save_file',0);


% The following function is the wrapper for sabcondv3_pub
c=202;
[out] = sabcondv3_pub_column_test(obs_id,c,'t_mode',2,...
    'WEIGHT_MODE',0,'lambda_a',0.01,'opt_img','TRRB','OPTBP','pri',...
    'nIter',5,'Bands_Opt',4,'OPT_CRISMTYPELIB',4,'OPT_SPLIBUSGS',6,...
    'PRECISION','single','PROC_MODE','CPU_2');